
Write-Warning ""
Write-Warning "*******************************************************************"
Write-Warning "*******************************************************************"
Write-Warning "**  This Chocolatey Packge ID `"win32-openssh`" is Depreciated.  **"
Write-Warning "**  Please re-run using `"openssh`" instead.                     **"
Write-Warning "*******************************************************************"
Write-Warning "*******************************************************************"
Write-Warning ""
Write-Warning "NOTE: This package does not use a pass through dependency to the "
Write-Warning "new package because most individuals are looking to install the "
Write-Warning "SSH Server feature and dependency packages cannot take "
Write-Warning "parameters to enable that feature."
